### ISSUE TITLE
Allow export of CSV/TSV from python API

### ISSUE THREAD

**Issue by rmcolq** [CLIMB-TRE/onyx-client#41]

**Comment by tombch** [comment]
Any more details as to how this would be most useful? Converting the retrieved data to a csv/tsv and writing to a file can be done pretty straightforwardly using python's builtin `csv.DictWriter`. Are you thinking some kind of parameter e.g. `file_path` that writes the data to a file without the user having to run `with open(...)`?

**Comment by rmcolq** [comment]
I was mostly thinking that having a TSV/CSV output is likely to be a common end point and therefore if you want some sort of uniformity between the API and the CLI then it should be in both. It wasn't obvious to me that I could use the csv.DictWriter, although now you mention it, I guess that makes sense! If you don't add this, provide some example in the documentation for others who don't make the jump like me

**Comment by tombch** [comment]
I have thought about it some more and I'm going to add something! Will have a go with something like a `OnyxClient.to_csv` class method for now. Does seem like a common use case so yeah I can see it being handy

**Comment by tombch** [comment]
I think I forgot to close this issue as a `to_csv` function was added in #43 some time ago. 

Documentation can be found here: https://climb-tre.github.io/onyx-client/api/documentation/client/#onyx.OnyxClient.to_csv
