### ISSUE TITLE
After a filter, enable a restricted number of fields to be returned (or make a second command that could be pipe-connected?)

### ISSUE THREAD

**Issue by rmcolq** [CLIMB-TRE/onyx-client#42]
e.g. I'd like to filter the data to a subset that meet my criteria, and would then like to export a table containing just the `sample_id`, `report` and `taxon.human_readable` columns

**Comment by tombch** [comment]
Yep that is the case. The `--include` and `--exclude` flags can be shortened to `-i` and `-e` respectively if that helps. Will have more of a think as to other ways to improve this

**Comment by warrickball** [comment]
My "Getting Started" example for the main docs site demonstrates the `--include` flag and mentions the `--exclude` flag as its converse. I also include the trick of using [bash brace expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) to shorten multiple inclusions. e.g.
```
--include={batch_id,bioinformatics_protocol}
```
is equivalent to
```
--include=batch_id --include=bioinformatics_protocol
```

**Comment by tombch** [comment]
Wow never knew of the bash brace expension before! Very useful thanks :)

**Comment by tombch** [comment]
Closing this issue because the `--include` and `--exclude` flags support multiple inputs now, e.g.
```
--include batch_id,bioinformatics_protocol
```
